config/routes.rb
InternRequestApp::Application.routes.draw do
  resources :intern_requests

  resources :intern_questions

  resources :enrichment_acts

  resources :intern_requests

  resources :interviewers

  resources :internship_locations

  resources :statuses

  resources :counties

  resources :addresses

  resources :departments

  resources :jobs

  resources :contacts

  resources :login_users

  resources :agencies

  resources :mentors

  resources :authorized_people









  root :to => 'intern_requests#index'


end


app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :city, :state, :StreetName, :StreetNumber, :zip
  
  belongs_to :agency
  belongs_to :contact
  has_many :intern_requests
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :AgencyName, :email, :phone
  
  has_many :mentors
  has_many :AuthorizedPeople
  has_many :contacts
  has_many :addresses
  has_many :departments
  has_many :intern_requests
  has_many :internship_locations
  
  
  
  belongs_to :county
  
  
end

app/models/authorized_person.rb
class AuthorizedPerson < ActiveRecord::Base
  attr_accessible :FirstName, :LastName, :department, :email, :phone, :title
  
  belongs_to :agency
  has_many :intern_requests
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :Email, :FirstName, :LastName, :phone
  
  belongs_to :agency
  has_one :address
  has_many :intern_requests
  
end

app/models/county.rb
class County < ActiveRecord::Base
  attr_accessible :CountyName
  
  has_many :agencies
  has_many :internship_locations
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :Name
  
  belongs_to :agency
  has_many :intern_requests
end

app/models/enrichment_act.rb
class EnrichmentAct < ActiveRecord::Base
  attr_accessible :desc, :name
  
  has_and_belongs_to_many :intern_requests
end

app/models/intern_question.rb
class InternQuestion < ActiveRecord::Base
  attr_accessible :name, :value
  
  has_and_belongs_to_many :intern_requests
end

app/models/intern_request.rb
class InternRequest < ActiveRecord::Base
  attr_accessible :EndDate, :EndHour, :EveningMeetingsPercent, :InternProjectDesc, :InternProvisionEmail, :InternProvisionPhone, :OfficeDutiesPercent, :OutFieldWorkPercent, :StartDate, :StartHour, :WeekendWorkPercent
  
  has_and_belongs_to_many :enrichment_acts
  has_and_belongs_to_many :intern_questions
  
  belongs_to :agency
  belongs_to :job
  belongs_to :department
  belongs_to :mentor
  belongs_to :authorized_person
  belongs_to :contact
  belongs_to :internship_location
  belongs_to :status
  belongs_to :address
  belongs_to :interviewer
  
  
end

app/models/interviewer.rb
class Interviewer < ActiveRecord::Base
  attr_accessible :email, :FirstName, :LastName, :phone, :title
  
  has_many :intern_requests
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :Enddate, :JobDesc, :Job_title, :RequiredSkills_1, :RequiredSkills_2, :RequiredSkills_3, :Startdate
  
  has_many :intern_requests
end

app/models/login_user.rb
class LoginUser < ActiveRecord::Base
  attr_accessible :Login, :Password, :Email
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  attr_accessible :FirstName, :LastName, :department, :email, :phone, :title
  
  belongs_to :agency
  has_many :intern_requests
  
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :StatusDescription
  
  has_many :intern_requests
end

app/controllers/statuses_controller.rb

class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :StatusDescription %><br />
    <%= f.text_field :StatusDescription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <tr>
    <th>Statusdescription</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  <tr>
    <td><%= status.StatusDescription %></td>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><%= link_to 'Destroy', status, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Statusdescription:</b>
  <%= @status.StatusDescription %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>