config/routes.rb
InternRequestApp::Application.routes.draw do
  resources :intern_requests

  resources :intern_questions

  resources :enrichment_acts

  resources :intern_requests

  resources :interviewers

  resources :internship_locations

  resources :statuses

  resources :counties

  resources :addresses

  resources :departments

  resources :jobs

  resources :contacts

  resources :login_users

  resources :agencies

  resources :mentors

  resources :authorized_people









  root :to => 'intern_requests#index'


end


app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :city, :state, :StreetName, :StreetNumber, :zip
  
  belongs_to :agency
  belongs_to :contact
  has_many :intern_requests
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :AgencyName, :email, :phone
  
  has_many :mentors
  has_many :AuthorizedPeople
  has_many :contacts
  has_many :addresses
  has_many :departments
  has_many :intern_requests
  has_many :internship_locations
  
  
  
  belongs_to :county
  
  
end

app/models/authorized_person.rb
class AuthorizedPerson < ActiveRecord::Base
  attr_accessible :FirstName, :LastName, :department, :email, :phone, :title
  
  belongs_to :agency
  has_many :intern_requests
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :Email, :FirstName, :LastName, :phone
  
  belongs_to :agency
  has_one :address
  has_many :intern_requests
  
end

app/models/county.rb
class County < ActiveRecord::Base
  attr_accessible :CountyName
  
  has_many :agencies
  has_many :internship_locations
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :Name
  
  belongs_to :agency
  has_many :intern_requests
end

app/models/enrichment_act.rb
class EnrichmentAct < ActiveRecord::Base
  attr_accessible :desc, :name
  
  has_and_belongs_to_many :intern_requests
end

app/models/intern_question.rb
class InternQuestion < ActiveRecord::Base
  attr_accessible :name, :value
  
  has_and_belongs_to_many :intern_requests
end

app/models/intern_request.rb
class InternRequest < ActiveRecord::Base
  attr_accessible :EndDate, :EndHour, :EveningMeetingsPercent, :InternProjectDesc, :InternProvisionEmail, :InternProvisionPhone, :OfficeDutiesPercent, :OutFieldWorkPercent, :StartDate, :StartHour, :WeekendWorkPercent
  
  has_and_belongs_to_many :enrichment_acts
  has_and_belongs_to_many :intern_questions
  
  belongs_to :agency
  belongs_to :job
  belongs_to :department
  belongs_to :mentor
  belongs_to :authorized_person
  belongs_to :contact
  belongs_to :internship_location
  belongs_to :status
  belongs_to :address
  belongs_to :interviewer
  
  
end

app/models/interviewer.rb
class Interviewer < ActiveRecord::Base
  attr_accessible :email, :FirstName, :LastName, :phone, :title
  
  has_many :intern_requests
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :Enddate, :JobDesc, :Job_title, :RequiredSkills_1, :RequiredSkills_2, :RequiredSkills_3, :Startdate
  
  has_many :intern_requests
end

app/models/login_user.rb
class LoginUser < ActiveRecord::Base
  attr_accessible :Login, :Password, :Email
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  attr_accessible :FirstName, :LastName, :department, :email, :phone, :title
  
  belongs_to :agency
  has_many :intern_requests
  
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :StatusDescription
  
  has_many :intern_requests
end

app/controllers/agencies_controller.rb

class AgenciesController < ApplicationController
  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agencies }
    end
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
    @agency = Agency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agency }
    end
  end

  # GET /agencies/new
  # GET /agencies/new.json
  def new
    @agency = Agency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agency }
    end
  end

  # GET /agencies/1/edit
  def edit
    @agency = Agency.find(params[:id])
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(params[:agency])

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render json: @agency, status: :created, location: @agency }
      else
        format.html { render action: "new" }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agencies/1
  # PUT /agencies/1.json
  def update
    @agency = Agency.find(params[:id])

    respond_to do |format|
      if @agency.update_attributes(params[:agency])
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency = Agency.find(params[:id])
    @agency.destroy

    respond_to do |format|
      format.html { redirect_to agencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/navigation_helper.rb
# modify from The Rails View
module NavigationHelper

  def nav_tab(title, url, options = {})
    puts"\n options is #{options}"
    current_tab = options.delete(:current)
    puts"\n current_tab is #{current_tab}"
    options[:class] = (current_tab == title) ? 'active' : 'inactive'
    content_tag(:li, link_to(title, url), options)
  end

  def current_at_tab(tab)
    puts "Current at tab: #{tab}"
    render partial: 'layouts/main_nav', locals: {current_tab: tab}
  end

end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/agencies/_form.html.erb
<%= form_for(@agency) do |f| %>
  <% if @agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% @agency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :AgencyName %><br />
    <%= f.text_field :AgencyName %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Editing agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<h1>Listing agencies</h1>

<table>
  <tr>
    <th>Agencyname</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= current_at_tab 'Agencies' %>

<% @agencies.each do |agency| %>
  <tr>
    <td><%= agency.AgencyName %></td>
    <td><%= agency.phone %></td>
    <td><%= agency.email %></td>
    <td><%= link_to 'Show', agency %></td>
    <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
    <td><%= link_to 'Destroy', agency, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Agency', new_agency_path %>

app/views/agencies/new.html.erb
<h1>New agency</h1>

<%= render 'form' %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Agencyname:</b>
  <%= @agency.AgencyName %>
</p>

<p>
  <b>Phone:</b>
  <%= @agency.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @agency.email %>
</p>


<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>