config/routes.rb
InternRequestApp::Application.routes.draw do
  resources :intern_requests

  resources :intern_questions

  resources :enrichment_acts

  resources :intern_requests

  resources :interviewers

  resources :internship_locations

  resources :statuses

  resources :counties

  resources :addresses

  resources :departments

  resources :jobs

  resources :contacts

  resources :login_users

  resources :agencies

  resources :mentors

  resources :authorized_people









  root :to => 'intern_requests#index'


end


app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :city, :state, :StreetName, :StreetNumber, :zip
  
  belongs_to :agency
  belongs_to :contact
  has_many :intern_requests
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :AgencyName, :email, :phone
  
  has_many :mentors
  has_many :AuthorizedPeople
  has_many :contacts
  has_many :addresses
  has_many :departments
  has_many :intern_requests
  has_many :internship_locations
  
  
  
  belongs_to :county
  
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :Email, :FirstName, :LastName, :phone
  
  belongs_to :agency
  has_one :address
  has_many :intern_requests
  
end

app/models/county.rb
class County < ActiveRecord::Base
  attr_accessible :CountyName
  
  has_many :agencies
  has_many :internship_locations
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :Name
  
  belongs_to :agency
  has_many :intern_requests
end

app/models/enrichment_act.rb
class EnrichmentAct < ActiveRecord::Base
  attr_accessible :desc, :name
  
  has_and_belongs_to_many :intern_requests
end

app/models/intern_question.rb
class InternQuestion < ActiveRecord::Base
  attr_accessible :name, :value
  
  has_and_belongs_to_many :intern_requests
end

app/models/intern_request.rb
class InternRequest < ActiveRecord::Base
  attr_accessible :EndDate, :EndHour, :EveningMeetingsPercent, :InternProjectDesc, :InternProvisionEmail, :InternProvisionPhone, :OfficeDutiesPercent, :OutFieldWorkPercent, :StartDate, :StartHour, :WeekendWorkPercent
  
  has_and_belongs_to_many :enrichment_acts
  has_and_belongs_to_many :intern_questions
  
  belongs_to :agency
  belongs_to :job
  belongs_to :department
  belongs_to :mentor
  belongs_to :authorized_person
  belongs_to :contact
  belongs_to :internship_location
  belongs_to :status
  belongs_to :address
  belongs_to :interviewer
  
  
end

app/models/internship_location.rb
class InternshipLocation < ActiveRecord::Base
  attr_accessible :phone
  
  has_many :intern_requests
  belongs_to :agency
  belongs_to :county
  
end

app/models/interviewer.rb
class Interviewer < ActiveRecord::Base
  attr_accessible :email, :FirstName, :LastName, :phone, :title
  
  has_many :intern_requests
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :Enddate, :JobDesc, :Job_title, :RequiredSkills_1, :RequiredSkills_2, :RequiredSkills_3, :Startdate
  
  has_many :intern_requests
end

app/models/login_user.rb
class LoginUser < ActiveRecord::Base
  attr_accessible :Login, :Password, :Email
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  attr_accessible :FirstName, :LastName, :department, :email, :phone, :title
  
  belongs_to :agency
  has_many :intern_requests
  
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :StatusDescription
  
  has_many :intern_requests
end

app/controllers/internship_locations_controller.rb

class InternshipLocationsController < ApplicationController
  # GET /internship_locations
  # GET /internship_locations.json
  def index
    @internship_locations = InternshipLocation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @internship_locations }
    end
  end

  # GET /internship_locations/1
  # GET /internship_locations/1.json
  def show
    @internship_location = InternshipLocation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @internship_location }
    end
  end

  # GET /internship_locations/new
  # GET /internship_locations/new.json
  def new
    @internship_location = InternshipLocation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @internship_location }
    end
  end

  # GET /internship_locations/1/edit
  def edit
    @internship_location = InternshipLocation.find(params[:id])
  end

  # POST /internship_locations
  # POST /internship_locations.json
  def create
    @internship_location = InternshipLocation.new(params[:internship_location])

    respond_to do |format|
      if @internship_location.save
        format.html { redirect_to @internship_location, notice: 'Internship location was successfully created.' }
        format.json { render json: @internship_location, status: :created, location: @internship_location }
      else
        format.html { render action: "new" }
        format.json { render json: @internship_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /internship_locations/1
  # PUT /internship_locations/1.json
  def update
    @internship_location = InternshipLocation.find(params[:id])

    respond_to do |format|
      if @internship_location.update_attributes(params[:internship_location])
        format.html { redirect_to @internship_location, notice: 'Internship location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @internship_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internship_locations/1
  # DELETE /internship_locations/1.json
  def destroy
    @internship_location = InternshipLocation.find(params[:id])
    @internship_location.destroy

    respond_to do |format|
      format.html { redirect_to internship_locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/internship_locations_helper.rb
module InternshipLocationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/internship_locations/_form.html.erb
<%= form_for(@internship_location) do |f| %>
  <% if @internship_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@internship_location.errors.count, "error") %> prohibited this internship_location from being saved:</h2>

      <ul>
      <% @internship_location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/internship_locations/edit.html.erb
<h1>Editing internship_location</h1>

<%= render 'form' %>

<%= link_to 'Show', @internship_location %> |
<%= link_to 'Back', internship_locations_path %>

app/views/internship_locations/index.html.erb
<h1>Listing internship_locations</h1>

<table>
  <tr>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= current_at_tab 'Internship_locations' %>

<% @internship_locations.each do |internship_location| %>
  <tr>
    <td><%= internship_location.phone %></td>
    <td><%= link_to 'Show', internship_location %></td>
    <td><%= link_to 'Edit', edit_internship_location_path(internship_location) %></td>
    <td><%= link_to 'Destroy', internship_location, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Internship location', new_internship_location_path %>

app/views/internship_locations/new.html.erb
<h1>New internship_location</h1>

<%= render 'form' %>

<%= link_to 'Back', internship_locations_path %>

app/views/internship_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phone:</b>
  <%= @internship_location.phone %>
</p>


<%= link_to 'Edit', edit_internship_location_path(@internship_location) %> |
<%= link_to 'Back', internship_locations_path %>