config/routes.rb
InternRequestApp::Application.routes.draw do
  resources :intern_requests

  resources :intern_questions

  resources :enrichment_acts

  resources :intern_requests

  resources :interviewers

  resources :internship_locations

  resources :statuses

  resources :counties

  resources :addresses

  resources :departments

  resources :jobs

  resources :contacts

  resources :login_users

  resources :agencies

  resources :mentors

  resources :authorized_people









  root :to => 'intern_requests#index'


end


app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :city, :state, :StreetName, :StreetNumber, :zip
  
  belongs_to :agency
  belongs_to :contact
  has_many :intern_requests
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :AgencyName, :email, :phone
  
  has_many :mentors
  has_many :AuthorizedPeople
  has_many :contacts
  has_many :addresses
  has_many :departments
  has_many :intern_requests
  has_many :internship_locations
  
  
  
  belongs_to :county
  
  
end

app/models/authorized_person.rb
class AuthorizedPerson < ActiveRecord::Base
  attr_accessible :FirstName, :LastName, :department, :email, :phone, :title
  
  belongs_to :agency
  has_many :intern_requests
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :Email, :FirstName, :LastName, :phone
  
  belongs_to :agency
  has_one :address
  has_many :intern_requests
  
end

app/models/county.rb
class County < ActiveRecord::Base
  attr_accessible :CountyName
  
  has_many :agencies
  has_many :internship_locations
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :Name
  
  belongs_to :agency
  has_many :intern_requests
end

app/models/enrichment_act.rb
class EnrichmentAct < ActiveRecord::Base
  attr_accessible :desc, :name
  
  has_and_belongs_to_many :intern_requests
end

app/models/intern_question.rb
class InternQuestion < ActiveRecord::Base
  attr_accessible :name, :value
  
  has_and_belongs_to_many :intern_requests
end

app/models/intern_request.rb
class InternRequest < ActiveRecord::Base
  attr_accessible :EndDate, :EndHour, :EveningMeetingsPercent, :InternProjectDesc, :InternProvisionEmail, :InternProvisionPhone, :OfficeDutiesPercent, :OutFieldWorkPercent, :StartDate, :StartHour, :WeekendWorkPercent
  
  has_and_belongs_to_many :enrichment_acts
  has_and_belongs_to_many :intern_questions
  
  belongs_to :agency
  belongs_to :job
  belongs_to :department
  belongs_to :mentor
  belongs_to :authorized_person
  belongs_to :contact
  belongs_to :internship_location
  belongs_to :status
  belongs_to :address
  belongs_to :interviewer
  
  
end

app/models/interviewer.rb
class Interviewer < ActiveRecord::Base
  attr_accessible :email, :FirstName, :LastName, :phone, :title
  
  has_many :intern_requests
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :Enddate, :JobDesc, :Job_title, :RequiredSkills_1, :RequiredSkills_2, :RequiredSkills_3, :Startdate
  
  has_many :intern_requests
end

app/models/login_user.rb
class LoginUser < ActiveRecord::Base
  attr_accessible :Login, :Password, :Email
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  attr_accessible :FirstName, :LastName, :department, :email, :phone, :title
  
  belongs_to :agency
  has_many :intern_requests
  
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :StatusDescription
  
  has_many :intern_requests
end

app/controllers/intern_questions_controller.rb

class InternQuestionsController < ApplicationController
  # GET /intern_questions
  # GET /intern_questions.json
  def index
    @intern_questions = InternQuestion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @intern_questions }
    end
  end

  # GET /intern_questions/1
  # GET /intern_questions/1.json
  def show
    @intern_question = InternQuestion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @intern_question }
    end
  end

  # GET /intern_questions/new
  # GET /intern_questions/new.json
  def new
    @intern_question = InternQuestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @intern_question }
    end
  end

  # GET /intern_questions/1/edit
  def edit
    @intern_question = InternQuestion.find(params[:id])
  end

  # POST /intern_questions
  # POST /intern_questions.json
  def create
    @intern_question = InternQuestion.new(params[:intern_question])

    respond_to do |format|
      if @intern_question.save
        format.html { redirect_to @intern_question, notice: 'Intern question was successfully created.' }
        format.json { render json: @intern_question, status: :created, location: @intern_question }
      else
        format.html { render action: "new" }
        format.json { render json: @intern_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /intern_questions/1
  # PUT /intern_questions/1.json
  def update
    @intern_question = InternQuestion.find(params[:id])

    respond_to do |format|
      if @intern_question.update_attributes(params[:intern_question])
        format.html { redirect_to @intern_question, notice: 'Intern question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @intern_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intern_questions/1
  # DELETE /intern_questions/1.json
  def destroy
    @intern_question = InternQuestion.find(params[:id])
    @intern_question.destroy

    respond_to do |format|
      format.html { redirect_to intern_questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/intern_questions_helper.rb
module InternQuestionsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/intern_questions/_form.html.erb
<%= form_for(@intern_question) do |f| %>
  <% if @intern_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intern_question.errors.count, "error") %> prohibited this intern_question from being saved:</h2>

      <ul>
      <% @intern_question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.check_box :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/intern_questions/edit.html.erb
<h1>Editing intern_question</h1>

<%= render 'form' %>

<%= link_to 'Show', @intern_question %> |
<%= link_to 'Back', intern_questions_path %>

app/views/intern_questions/index.html.erb
<h1>Listing intern_questions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= current_at_tab 'Intern_questions' %>

<% @intern_questions.each do |intern_question| %>
  <tr>
    <td><%= intern_question.name %></td>
    <td><%= intern_question.value %></td>
    <td><%= link_to 'Show', intern_question %></td>
    <td><%= link_to 'Edit', edit_intern_question_path(intern_question) %></td>
    <td><%= link_to 'Destroy', intern_question, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Intern question', new_intern_question_path %>

app/views/intern_questions/new.html.erb
<h1>New intern_question</h1>

<%= render 'form' %>

<%= link_to 'Back', intern_questions_path %>

app/views/intern_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @intern_question.name %>
</p>

<p>
  <b>Value:</b>
  <%= @intern_question.value %>
</p>


<%= link_to 'Edit', edit_intern_question_path(@intern_question) %> |
<%= link_to 'Back', intern_questions_path %>